version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: people-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: michaelelison
      POSTGRES_PASSWORD: bob
      POSTGRES_DB: people
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
